# constantes.py
import pygame

# Dimensões do Grid e Célula
NUM_LINHAS_MAPA_PADRAO = 25
NUM_COLUNAS_MAPA_PADRAO = 40
TAMANHO_CELULA = 20

# Cores (formato RGB)
BRANCO = (255, 255, 255)
PRETO = (0, 0, 0)
CINZA = (200, 200, 200)
CINZA_ESCURO = (160, 160, 160)

COR_RUA = (220, 220, 220)
COR_CONSTRUCAO = (100, 100, 100)
COR_PARTIDA = (0, 200, 0)
COR_CHEGADA = (200, 0, 0)
COR_CARRO = (50, 50, 200)

# Cores para o caminho sugerido e tráfego
VERDE_CAMINHO = (60, 179, 113)
AMARELO_CAMINHO = (255, 215, 0)
LARANJA_CAMINHO = (255, 140, 0)
VERMELHO_CAMINHO = (220, 20, 60)
COR_ACIDENTE_VISUAL = (75, 0, 130)

# Tipos de Célula
TIPO_RUA = 0
TIPO_CONSTRUCAO = 1
TIPO_PARTIDA = 2
TIPO_CHEGADA = 3
TIPO_CAMINHO_SUGERIDO = 5

# Tipos de Eventos de Tráfego
TIPO_RUA_LIVRE = 10
TIPO_RUA_ENGARRAFAMENTO_LEVE = 11
TIPO_RUA_ENGARRAFAMENTO_MODERADO = 12
TIPO_RUA_ENGARRAFAMENTO_PESADO = 13
TIPO_RUA_ACIDENTE = 14

# Custos de Movimento Associados (para Pathfinder)
CUSTO_LIVRE = 1
CUSTO_ENG_LEVE = 3
CUSTO_ENG_MODERADO = 6
CUSTO_ENG_PESADO = 10
CUSTO_ACIDENTE = float('inf')

# Dimensões da Tela e Painel de UI
LARGURA_MAPA = NUM_COLUNAS_MAPA_PADRAO * TAMANHO_CELULA
ALTURA_MAPA = NUM_LINHAS_MAPA_PADRAO * TAMANHO_CELULA

ALTURA_PAINEL_UI = 100
LARGURA_TELA = LARGURA_MAPA
ALTURA_TELA = ALTURA_MAPA + ALTURA_PAINEL_UI

# Jogo e Simulação
FPS = 30
EVENTO_ATUALIZAR_TRAFEGO = pygame.USEREVENT + 1
INTERVALO_ATUALIZACAO_TRAFEGO = 2500

# Configurações da UI
COR_PAINEL_UI = (50, 50, 50)
COR_TEXTO_UI = (240, 240, 240)
TAMANHO_FONTE_UI_PADRAO = 24
TAMANHO_FONTE_NOTIFICACAO = 20

# Pincel Editor
PINCEL_RUA = TIPO_RUA
PINCEL_CONSTRUCAO = TIPO_CONSTRUCAO
PINCEL_REMOVER_EVENTO = 99

# Geração de Mapa Procedural (Mantido, mas não usado por padrão)
DENSIDADE_CONSTRUCAO = 0.20
MIN_COMPRIMENTO_RUA = 3
MAX_COMPRIMENTO_RUA = 7

# Carro
VELOCIDADE_BASE_CARRO_TICKS = 10
MODIFICADOR_VEL_ENG_LEVE = 1.5
MODIFICADOR_VEL_ENG_MODERADO = 2.5
MODIFICADOR_VEL_ENG_PESADO = 4.0

# Direções para o carro
DIRECAO_NENHUMA = -1
DIRECAO_CIMA = 0
DIRECAO_BAIXO = 1
DIRECAO_ESQUERDA = 2
DIRECAO_DIREITA = 3

# Estados do Jogo
ESTADO_MENU_INICIAL = 0
ESTADO_MODO_EDITOR = 1
ESTADO_SIMULACAO = 2
ESTADO_SAINDO = 3